version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=phoenix_portal
    ports:
      - 4000:5432
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - 5672:5672
    networks:
      - app-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
      - redis
      - rabbitmq
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    name: app-network